package cv.igrp.framework.auth.core.processor;

import com.google.auto.service.AutoService;
import com.squareup.javapoet.*;
import cv.igrp.framework.stereotype.IgrpPermission;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import java.util.logging.*;

/**
 * Annotation processor that scans for @IgrpPermission
 * and generates a PermissionsRegistry class.
 */
@AutoService(Processor.class)
@SupportedAnnotationTypes("cv.igrp.framework.stereotype.IgrpPermission")
@SupportedSourceVersion(SourceVersion.RELEASE_21)
@SuppressWarnings("unused")
public class PermissionSourceGenerator extends AbstractProcessor {

    private final Logger log = Logger.getLogger(PermissionSourceGenerator.class.getName());

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (annotations.isEmpty()) return false;

        // Track permission names to detect duplicates
        Set<String> seenNames = new HashSet<>();

        TypeSpec.Builder registry = TypeSpec.classBuilder("PermissionsRegistry")
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addJavadoc("Auto-generated by iGRP Source Generator. DO NOT EDIT.\n");

        TypeSpec.Builder enumBuilder = TypeSpec.enumBuilder("Permission")
                .addModifiers(Modifier.PUBLIC);

        for (Element element : roundEnv.getElementsAnnotatedWith(IgrpPermission.class)) {
            IgrpPermission ann = element.getAnnotation(IgrpPermission.class);
            if (ann == null) continue;

            String rawName = ann.name().trim();

            // Check for duplicate names (case-insensitive to be extra safe)
            String duplicateKey = rawName.toLowerCase(Locale.ROOT);
            if (!seenNames.add(duplicateKey)) {
                processingEnv.getMessager().printMessage(
                        Diagnostic.Kind.WARNING,
                        "Duplicate @IgrpPermission name detected: '" + rawName + "' — each permission name must be unique.",
                        element
                );
                continue;
            }

            // Build enum constant name safely (convert invalid chars)
            String constName = rawName
                    .toUpperCase(Locale.ROOT)
                    .replaceAll("[^A-Z0-9_]", "_");

            // Guarantee uniqueness of enum constant itself (e.g., if two different names normalize to same const)
            while (seenNames.contains(constName)) {
                constName = constName + "_DUP";
            }

            String desc = ann.description().isEmpty() ? rawName : ann.description();
            boolean enabled = ann.enabled();

            enumBuilder.addEnumConstant(constName,
                    TypeSpec.anonymousClassBuilder("$S, $S, $L", rawName, desc, enabled).build());
        }

        enumBuilder.addField(String.class, "code", Modifier.PRIVATE, Modifier.FINAL);
        enumBuilder.addField(String.class, "description", Modifier.PRIVATE, Modifier.FINAL);
        enumBuilder.addField(boolean.class, "enabled", Modifier.PRIVATE, Modifier.FINAL);

        enumBuilder.addMethod(MethodSpec.constructorBuilder()
                .addParameter(String.class, "code")
                .addParameter(String.class, "description")
                .addParameter(boolean.class, "enabled")
                .addStatement("this.code = code")
                .addStatement("this.description = description")
                .addStatement("this.enabled = enabled")
                .build());

        enumBuilder.addMethod(MethodSpec.methodBuilder("getCode")
                .returns(String.class)
                .addModifiers(Modifier.PUBLIC)
                .addStatement("return code")
                .build());

        enumBuilder.addMethod(MethodSpec.methodBuilder("getDescription")
                .returns(String.class)
                .addModifiers(Modifier.PUBLIC)
                .addStatement("return description")
                .build());

        enumBuilder.addMethod(MethodSpec.methodBuilder("enabled")
                .returns(boolean.class)
                .addModifiers(Modifier.PUBLIC)
                .addStatement("return enabled")
                .build());

        registry.addType(enumBuilder.build());

        JavaFile javaFile = JavaFile.builder("cv.igrp.framework.auth.generated", registry.build())
                .indent("    ")
                .build();

        try {
            javaFile.writeTo(processingEnv.getFiler());
            log.info("Generated PermissionsRegistry successfully.");
        } catch (IOException e) {
            log.log(Level.SEVERE, "Failed to write PermissionsRegistry: " + e.getMessage());
            return false;
        }

        return true;
    }
}