# General
spring.config.import=optional:file:.env[.properties]

server.port=${SERVICE_PORT:8081}

permify.server.url=${PERMIFY_SERVER_URL:http://localhost:3476}
permify.api.key=${PERMIFY_API_KEY_URL:} # If not Set should result in an empty String.

