<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <parent>
        <groupId>cv.igrp.framework.auth</groupId>
        <artifactId>backend</artifactId>
        <version>0.1.0-beta.2</version>
    </parent>

    <artifactId>keycloak</artifactId>
    <description>iGRP 3.0 Framework Auth Keycloak</description>
    <url>https://igrp.cv</url>

    <properties>
        <version.keycloak>26.0.5</version.keycloak>
    </properties>

    <dependencies>
        <!-- IGRP IAM Core Dependencies -->
        <dependency>
            <groupId>cv.igrp.framework.auth</groupId>
            <artifactId>core</artifactId>
            <version>0.1.0-beta.2</version>
        </dependency>

        <!-- Keycloak Dependencies -->
        <!-- https://mvnrepository.com/artifact/org.keycloak/keycloak-admin-client -->
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-admin-client</artifactId>
            <version>${version.keycloak}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.17</version>
        </dependency>
        <!-- SLF4J Binding for Logback -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.17</version>
            <scope>runtime</scope>
        </dependency>

    </dependencies>

</project>
